version: '3'
services:
  app:
    build: .
    container_name: flask_app
    environment:
      # set database credentials
      DB_HOST: mysql
      DB_NAME: flask
      DB_USER: flask
      DB_PASSWORD: testpassword
    links:
      - mysql
    depends_on:
      # build the db first
      - mysql
    #ports:
      # bind on  port 6000 on host ( to flask app on port 5000)
    #  - "6000:5000"

  mysql:
    container_name: flask_mysql
    image: mysql:5.7
    volumes:
#        # Mount local directory to the mysql container to persist data
      - ./db-data:/var/lib/mysql
    # ports:
    #   - "3306:3306"
    environment:
      # MySQL credentials
      MYSQL_ROOT_PASSWORD: testpassword
      MYSQL_DATABASE: flask
      MYSQL_USER: flask
      MYSQL_PASSWORD: testpassword

  nginx:
    build: ./nginx
    ports:
      - 1337:80
      - 8443:443
    depends_on:
      - app

#volumes:
#  # for persistence
#  mysql-data:
#    driver: local
